---
title: "Final_Project_1"
output: pdf_document
---

# Metropolis Hasting

 + function implementation
```{r}
target <- function(x){
  if ((x > 1) | (x < 0)){
    return(0)}
  else{
    return(dbeta(x, 6, 4))
  }
}

proposalfunction <- function(c, shape){

  return(rbeta(1, c * shape, c * (1 - shape)))
}

```

```{r}
run_metropolis_MCMC <- function(c, startvalue, iterations){
    chain <- rep(0, iterations)
    chain[1] <- startvalue
    for (i in 1:iterations){
        proposal <- proposalfunction(c, chain[i])
        correction <- dbeta(chain[i], c * proposal, c * (1- proposal))/ dbeta(proposal, c * proposal, c * (1 - proposal))
        probab <- (target(proposal) / target(chain[i]) )* correction
        if (runif(1) < probab){
            chain[i+1] = proposal
        }else{
            chain[i+1] = chain[i]
        }
    }
    return(chain)
}
 
```

### initial run: c = 1
```{r}
start <- runif(1, 0, 10)
samples1 <- run_metropolis_MCMC(1, start, 10000)
acceptance_rate1 <- 1 - mean(duplicated(samples1))
print(acceptance_rate1)

```


```{r}
 par(mfrow=c(1,3))  #1 row, 3 columns
 plot(samples1); acf(samples1); hist(samples1)  #plot commands
```


```{r}
hist(rbeta(10000,6,4))
```


### c = 0.1
```{r}
samples2 <- run_metropolis_MCMC(0.1, start, 10000)
acceptance_rate2 <- 1 - mean(duplicated(samples2))
print(acceptance_rate2)

```


```{r}
 par(mfrow=c(1,3))  #1 row, 3 columns
 plot(samples2); acf(samples2); hist(samples2)  #plot commands
```


### c = 2.5
```{r}
samples3 <- run_metropolis_MCMC(2.5, start, 10000)
acceptance_rate3 <- 1 - mean(duplicated(samples3))
print(acceptance_rate3)

```


```{r}
 par(mfrow=c(1,3))  #1 row, 3 columns
 plot(samples3); acf(samples3); hist(samples3)  #plot commands
```


### c = 10
```{r}
samples4 <- run_metropolis_MCMC(10, start, 10000)
acceptance_rate4 <- 1 - mean(duplicated(samples4))
print(acceptance_rate4)

```


```{r}
 par(mfrow=c(1,3))  #1 row, 3 columns
 plot(samples4); acf(samples4); hist(samples4)  #plot commands
```


### adding burn-in time
```{r}
burnIn <- 0.5 * 10000
acceptance1 <- 1 - mean(duplicated(samples1[-(1:burnIn)]))
acceptance2 <- 1 - mean(duplicated(samples2[-(1:burnIn)]))
acceptance3 <- 1 - mean(duplicated(samples3[-(1:burnIn)]))
acceptance4 <- 1 - mean(duplicated(samples4[-(1:burnIn)]))
```


