---
title: "Final_Project_P3_Yilun_Dai"
output: pdf_document
---

```{r}
install.packages('rattle')
data(wine, package="rattle")
```

```{r}
sample(1:nrow(wine), 3, replace = F)
```


```{r}
wine_complete <- na.omit(wine)

wine_data <- wine_complete[-1]
```

```{r}
euclidean_dist <- function(x1, x2){
  dist <- sqrt(sum((x1 - x2) ^ 2))
  return(dist)
}
```


```{r}
kmeans <- function(k, clustering_data) {
  num_samples <- nrow(clustering_data)
  centers <- clustering_data[sample(1:num_samples, k, replace = F), ]
  old_cluster <- numeric(num_samples)
  new_cluster <- rep(1, num_samples)
  while(any(old_cluster != new_cluster)){
    old_cluster <- new_cluster
    dist_mat <- matrix(0, num_samples, k)
    for (i in 1:k){
      for (j in 1:num_samples){
        dist_mat[j, i] <- euclidean_dist(clustering_data[j, ], centers[i, ])
      }
    }
    new_cluster <- apply(dist_mat, 1, which.min)
  }
  for (i in 1:k){
    centers[i, ] <- apply(clustering_data[which(new_cluster == i), ], 2, mean)
  }
  return(new_cluster)
}

```

```{r}
wine_cluster <- kmeans(3, wine_data)
```

```{r}
install.packages('/Users/yilundai/Documents/Documents/Fall2018/StatsComputingA/robustbase_0.93-1.1.tar', repose = NULL, type = 'source')
install.packages('fpc', dependencies = TRUE)
library(fpc)
```

```{r}
plotcluster(wine_data, wine_cluster)
```

 Yes, the result seems well-seperated. 
 
 + Quantify
 
```{r}
wine_type <- wine['Type']
wine_type <- as.numeric(apply(wine_type, 1, as.character))
```



