---
title: "Final Project Zhen Dai"
author: "Zhen Dai"
date: "October 31, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
data(wine, package="rattle")
library('fpc')

wine2 = wine[-1]

square = function(x) {x^2}
min_distance = function(center,train){
  m = dim(center)[1]
  dist_matrix = matrix(nrow = dim(train)[1], ncol = 3)
  center = as.matrix(center)
  for (i in 1:m){
    g = function(x){x - center[i,]}
    dist1 = apply(train, 1, g)
    dist1 = t(dist1)
    dist1 = apply(dist1, 2, square)
    dist1 = rowSums(dist1)
    dist_matrix[,i] = dist1
  }
  min_index = apply(dist_matrix, 1, which.min)
}
k_mean = function(k=3, train){
  n = dim(train)[1]
  random_index = as.integer(runif(k)*n)
  start = train[random_index,]
  while (TRUE){
    cluster_index = min_distance(center = start, train = train)
    start_new = start
    for (i in 1:k){
      cluster_i = train[cluster_index == i,]
      mean_i = apply(cluster_i, 2, mean)
      start_new[i,] = mean_i
    }
    if (sum(start_new != start) == 0){
      return(cluster_index)
    }
    start = start_new
  }
}

cluster1 = k_mean(train = wine2)
plotcluster(wine2, cluster1)
true_label1 = wine[,1]
plotcluster(wine2, true_label1)
true_label11 = true_label1
true_label11[true_label1 == 1] = 3
true_label11[true_label1 == 3] = 1
plotcluster(wine2, true_label11)
diff = sum(cluster1 != true_label11)/length(true_label11)
diff
#We make around 30% error in this case.

wine3 = scale(wine2)
cluster2 = k_mean(train = wine3)
plotcluster(wine3, cluster2)

data(iris)
iris2 = iris[,-5]
cluster3 = k_mean(train = iris2)
plotcluster(iris2, cluster3)

iris3 = scale(iris2)
cluster4 = k_mean(train = iris3)
plotcluster(iris3, cluster4)
```
